export enum SessionStatus {
  ACTIVE = 'ACTIVE',
  COLLECTING_INFO = 'COLLECTING_INFO',
  VALIDATING_CART = 'VALIDATING_CART',
  CHECKOUT_PROCESSING = 'CHECKOUT_PROCESSING',
  COMPLETED = 'COMPLETED',
  ABANDONED = 'ABANDONED',
  FAILED = 'FAILED',
}
